<?php $this->headTitle('Presentatie', 'PREPEND'); ?>

<h1>Presentatie</h1>

<p>Bij deze verhandeling hoort ook een presentatie. Mijn slides zijn
hier beschikbaar.</p>

<p>
	<a href="<?php echo $this->serverUrl() . $this->baseUrl(); ?>/pdf/cryptografie_presentatie_michiel_staessen.pdf">
		<img src="http://michielstaessen.be/static/icons/silk/page_white_acrobat.png" alt="PDF" /> Bekijken
	</a>
</p>

<p>
	<object id="__sse6991151" width="690" height="576">
		<param name="movie" value="http://static.slidesharecdn.com/swf/ssplayer2.swf?doc=cryptografie-110220073533-phpapp01&stripped_title=cryptografie-6991151&userName=mstaessen" />
		<param name="allowFullScreen" value="true" />
		<param name="allowScriptAccess" value="always" />
		<embed name="__sse6991151" src="http://static.slidesharecdn.com/swf/ssplayer2.swf?doc=cryptografie-110220073533-phpapp01&stripped_title=cryptografie-6991151&userName=mstaessen" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="690" height="576"></embed>
	</object>
</p>