<?php $this->headTitle('Verhandeling', 'PREPEND'); ?><h1>Verhandeling</h1>

<p>Deze site stelt uiteraard weinig voor zonder de uitleg die erbij
hoort. Daarom kan je hier mijn verhandeling downloaden.
</p>

<p>
	<a href="<?php echo $this->serverUrl() . $this->baseUrl(); ?>/pdf/cryptografie_verhandeling_michiel_staessen.pdf">
		<img src="http://michielstaessen.be/static/icons/silk/page_white_acrobat.png" alt="PDF" /> Bekijken
	</a>
</p>