<?php $this->headTitle('Demo', 'PREPEND'); ?>

<h1>Demo</h1>

<p>Om de werking van de diverse algoritmes te demonstreren, heb ik
enkele demo's in elkaar geknutseld in PHP.</p>

<h2>Symmetrische Cryptografie</h2>

<dl class="demo">
	<dt><a
		href="<?= $this->url(array('controller' => 'demo', 'action' => 'rot13'), null, true); ?>">Caesarvercijfering</a></dt>
	<dd>Dit algoritme verschuift elke letter 13 plaatsen. Een eenvoudige
	substitutie dus.</dd>

	<dt><a href="http://users.telenet.be/d.rijmenants/en/enigmasim.htm">Enigma</a></dt>
	<dd>Enigma, de codeermachine van de Duitsers, wordt niet uitbundig
	besproken in mijn werk. Er is wel een zeer interessant programmaatje te
	vinden op internet. Waarom het wiel ook opnieuw uitvinden?</dd>

	<dt><!--<a href="<?= $this->url(array('controller' => 'demo', 'action' => 'sdes')); ?>">-->S-DES
	(Nog niet in gebruik op de nieuwe site...)<!--</a>--></dt>
	<dd>S-DES is de vereenvoudigde variant van DES en maakt gebruik van
	substituties en permutaties. DES is het meest gebruikte algoritme
	binnen de symmetrische cryptografie.</dd>
</dl>

<h2>Asymmetrische Cryptografie</h2>

<h3>RSA</h3>

<p>Het bekendste algoritme van de asymmetrische cryptografie is
ongetwijfeld RSA. Hiervoor zijn meerdere demo's gemaakt.</p>

<dl>
	<dt><a
		href="<?= $this->url(array('controller' => 'demo', 'action' => 'ggd'));?>">Grootste
	Gemene Deler (GGD)</a></dt>
	<dd>Bereken de grootste gemene deler (GGD) van twee grote getallen</dd>

	<dt><a
		href="<?= $this->url(array('controller' => 'demo', 'action' => 'phi'));?>">Euler
	&Phi; functie</a></dt>
	<dd>Bereken de Euler &Phi; functie voor een getal</dd>

	<dt><a
		href="<?= $this->url(array('controller' => 'demo', 'action' => 'priemfactoren'));?>">Twee
	priemfactoren (e en d) vinden</a></dt>
	<dd>Zoek alle mogelijke waarden voor e en d aan de hand van n</dd>

	<dt><a
		href="<?= $this->url(array('controller' => 'demo', 'action' => 'rsa'));?>">Encryptie
	&amp; Decryptie</a></dt>
	<dd>De eigenlijke versleutelingsmechanismen</dd>
</dl>

<h3>Hashing</h3>
<dl>
	<dt><a
		href="<?= $this->url(array('controller' => 'demo', 'action' => 'md5'), null, true); ?>">MD5</a></dt>
	<dd>Het MD5 Hashalgoritme</dd>

	<dt><a
		href="<?= $this->url(array('controller' => 'demo', 'action' => 'sha1'), null, true); ?>">SHA1</a></dt>
	<dd>Het SHA1 Hashalgoritme</dd>
</dl>